define(['dart_sdk', 'packages/angular_components/annotations/rtl_annotation.template', 'packages/angular_components/app_layout/material_drawer_base.template', 'packages/angular_components/app_layout/material_persistent_drawer.template', 'packages/angular_components/app_layout/material_temporary_drawer.template', 'packages/angular_components/auto_dismiss/auto_dismiss.template', 'packages/angular_components/button_decorator/button_decorator.template', 'packages/angular_components/content/deferred_content.template', 'packages/angular_components/content/deferred_content_aware.template', 'packages/angular_components/dynamic_component/dynamic_component.template', 'packages/angular_components/focus/focus.template', 'packages/angular_components/focus/focus_activable_item.template', 'packages/angular_components/focus/focus_item.template', 'packages/angular_components/focus/focus_list.template', 'packages/angular_components/focus/focus_trap.template', 'packages/angular_components/focus/keyboard_only_focus_indicator.template', 'packages/angular_components/forms/error_renderer.template', 'packages/angular_components/glyph/glyph.template', 'packages/angular_components/highlighted_text/highlighted_text.template', 'packages/angular_components/highlighted_text/highlighted_value.template', 'packages/angular_components/laminate/components/modal/modal.template', 'packages/angular_components/laminate/enums/alignment.template', 'packages/angular_components/laminate/overlay/module.template', 'packages/angular_components/laminate/popup/module.template', 'packages/angular_components/laminate/popup/popup.template', 'packages/angular_components/material_button/material_button.template', 'packages/angular_components/material_button/material_button_base.template', 'packages/angular_components/material_button/material_fab.template', 'packages/angular_components/material_checkbox/material_checkbox.template', 'packages/angular_components/material_chips/material_chip.template', 'packages/angular_components/material_chips/material_chips.template', 'packages/angular_components/material_datepicker/calendar.template', 'packages/angular_components/material_datepicker/comparison.template', 'packages/angular_components/material_datepicker/date_input.template', 'packages/angular_components/material_datepicker/date_range_editor.template', 'packages/angular_components/material_datepicker/date_range_input.template', 'packages/angular_components/material_datepicker/material_calendar_picker.template', 'packages/angular_components/material_datepicker/material_date_range_picker.template', 'packages/angular_components/material_datepicker/material_date_time_picker.template', 'packages/angular_components/material_datepicker/material_datepicker.template', 'packages/angular_components/material_datepicker/material_month_picker.template', 'packages/angular_components/material_datepicker/material_time_picker.template', 'packages/angular_components/material_datepicker/model.template', 'packages/angular_components/material_datepicker/module.template', 'packages/angular_components/material_datepicker/next_prev_buttons.template', 'packages/angular_components/material_datepicker/preset.template', 'packages/angular_components/material_dialog/material_dialog.template', 'packages/angular_components/material_expansionpanel/material_expansionpanel.template', 'packages/angular_components/material_expansionpanel/material_expansionpanel_auto_dismiss.template', 'packages/angular_components/material_expansionpanel/material_expansionpanel_set.template', 'packages/angular_components/material_icon/material_icon.template', 'packages/angular_components/material_input/base_material_input.template', 'packages/angular_components/material_input/deferred_validator.template', 'packages/angular_components/material_input/input_wrapper.template', 'packages/angular_components/material_input/material_auto_suggest_input.template', 'packages/angular_components/material_input/material_input.template', 'packages/angular_components/material_input/material_input_default_value_accessor.template', 'packages/angular_components/material_input/material_input_error_keys.template', 'packages/angular_components/material_input/material_input_multiline.template', 'packages/angular_components/material_input/material_number_accessor.template', 'packages/angular_components/material_input/material_number_validators.template', 'packages/angular_components/material_input/material_percent_directive.template', 'packages/angular_components/material_list/material_list.template', 'packages/angular_components/material_list/material_list_item.template', 'packages/angular_components/material_list/material_list_size.template', 'packages/angular_components/material_menu/dropdown_menu.template', 'packages/angular_components/material_menu/material_fab_menu.template', 'packages/angular_components/material_menu/material_menu.template', 'packages/angular_components/material_menu/menu_item_affix_list.template', 'packages/angular_components/material_menu/menu_popup_wrapper.template', 'packages/angular_components/material_menu/menu_root.template', 'packages/angular_components/material_popup/material_popup.template', 'packages/angular_components/material_progress/material_progress.template', 'packages/angular_components/material_radio/material_radio.template', 'packages/angular_components/material_ripple/material_ripple.template', 'packages/angular_components/material_select/activation_handler.template', 'packages/angular_components/material_select/display_name.template', 'packages/angular_components/material_select/dropdown_button.template', 'packages/angular_components/material_select/material_dropdown_select.template', 'packages/angular_components/material_select/material_dropdown_select_accessor.template', 'packages/angular_components/material_select/material_select.template', 'packages/angular_components/material_select/material_select_base.template', 'packages/angular_components/material_select/material_select_dropdown_item.template', 'packages/angular_components/material_select/material_select_item.template', 'packages/angular_components/material_select/material_select_searchbox.template', 'packages/angular_components/material_select/shift_click_selection.template', 'packages/angular_components/material_spinner/material_spinner.template', 'packages/angular_components/material_tab/fixed_material_tab_strip.template', 'packages/angular_components/material_tab/material_tab.template', 'packages/angular_components/material_tab/material_tab_panel.template', 'packages/angular_components/material_tab/tab_button.template', 'packages/angular_components/material_tab/tab_change_event.template', 'packages/angular_components/material_tab/tab_mixin.template', 'packages/angular_components/material_toggle/material_toggle.template', 'packages/angular_components/material_tooltip/material_tooltip.template', 'packages/angular_components/material_tooltip/module.template', 'packages/angular_components/material_tree/material_tree.template', 'packages/angular_components/material_yes_no_buttons/material_yes_no_buttons.template', 'packages/angular_components/mixins/button_wrapper.template', 'packages/angular_components/mixins/focusable_mixin.template', 'packages/angular_components/mixins/has_tab_index.template', 'packages/angular_components/mixins/highlight_assistant_mixin.template', 'packages/angular_components/mixins/material_dropdown_base.template', 'packages/angular_components/mixins/track_layout_changes.template', 'packages/angular_components/model/date/date.template', 'packages/angular_components/model/selection/select.template', 'packages/angular_components/model/selection/selection_model.template', 'packages/angular_components/model/selection/selection_options.template', 'packages/angular_components/model/selection/string_selection_options.template', 'packages/angular_components/model/ui/display_name.template', 'packages/angular_components/model/ui/has_renderer.template', 'packages/angular_components/model/ui/icon.template', 'packages/angular_components/reorder_list/reorder_events.template', 'packages/angular_components/reorder_list/reorder_list.template', 'packages/angular_components/scorecard/scoreboard.template', 'packages/angular_components/scorecard/scorecard.template', 'packages/angular_components/stop_propagation/stop_propagation.template', 'packages/angular_components/theme/dark_theme.template', 'packages/angular_components/theme/module.template', 'packages/angular_components/utils/async/async.template'], function(dart_sdk, rtl_annotation, material_drawer_base, material_persistent_drawer, material_temporary_drawer, auto_dismiss, button_decorator, deferred_content, deferred_content_aware, dynamic_component, focus, focus_activable_item, focus_item, focus_list, focus_trap, keyboard_only_focus_indicator, error_renderer, glyph, highlighted_text, highlighted_value, modal, alignment, module, module$, popup, material_button, material_button_base, material_fab, material_checkbox, material_chip, material_chips, calendar, comparison, date_input, date_range_editor, date_range_input, material_calendar_picker, material_date_range_picker, material_date_time_picker, material_datepicker, material_month_picker, material_time_picker, model, module$0, next_prev_buttons, preset, material_dialog, material_expansionpanel, material_expansionpanel_auto_dismiss, material_expansionpanel_set, material_icon, base_material_input, deferred_validator, input_wrapper, material_auto_suggest_input, material_input, material_input_default_value_accessor, material_input_error_keys, material_input_multiline, material_number_accessor, material_number_validators, material_percent_directive, material_list, material_list_item, material_list_size, dropdown_menu, material_fab_menu, material_menu, menu_item_affix_list, menu_popup_wrapper, menu_root, material_popup, material_progress, material_radio, material_ripple, activation_handler, display_name, dropdown_button, material_dropdown_select, material_dropdown_select_accessor, material_select, material_select_base, material_select_dropdown_item, material_select_item, material_select_searchbox, shift_click_selection, material_spinner, fixed_material_tab_strip, material_tab, material_tab_panel, tab_button, tab_change_event, tab_mixin, material_toggle, material_tooltip, module$1, material_tree, material_yes_no_buttons, button_wrapper, focusable_mixin, has_tab_index, highlight_assistant_mixin, material_dropdown_base, track_layout_changes, date, select, selection_model, selection_options, string_selection_options, display_name$, has_renderer, icon, reorder_events, reorder_list, scoreboard, scorecard, stop_propagation, dark_theme, module$2, async) {
  'use strict';
  const core = dart_sdk.core;
  const dart = dart_sdk.dart;
  const dartx = dart_sdk.dartx;
  const annotations__rtl_annotation$46template = rtl_annotation.annotations__rtl_annotation$46template;
  const app_layout__material_drawer_base$46template = material_drawer_base.app_layout__material_drawer_base$46template;
  const app_layout__material_persistent_drawer$46template = material_persistent_drawer.app_layout__material_persistent_drawer$46template;
  const app_layout__material_temporary_drawer$46template = material_temporary_drawer.app_layout__material_temporary_drawer$46template;
  const auto_dismiss__auto_dismiss$46template = auto_dismiss.auto_dismiss__auto_dismiss$46template;
  const button_decorator__button_decorator$46template = button_decorator.button_decorator__button_decorator$46template;
  const content__deferred_content$46template = deferred_content.content__deferred_content$46template;
  const content__deferred_content_aware$46template = deferred_content_aware.content__deferred_content_aware$46template;
  const dynamic_component__dynamic_component$46template = dynamic_component.dynamic_component__dynamic_component$46template;
  const focus__focus$46template = focus.focus__focus$46template;
  const focus__focus_activable_item$46template = focus_activable_item.focus__focus_activable_item$46template;
  const focus__focus_item$46template = focus_item.focus__focus_item$46template;
  const focus__focus_list$46template = focus_list.focus__focus_list$46template;
  const focus__focus_trap$46template = focus_trap.focus__focus_trap$46template;
  const focus__keyboard_only_focus_indicator$46template = keyboard_only_focus_indicator.focus__keyboard_only_focus_indicator$46template;
  const forms__error_renderer$46template = error_renderer.forms__error_renderer$46template;
  const glyph__glyph$46template = glyph.glyph__glyph$46template;
  const highlighted_text__highlighted_text$46template = highlighted_text.highlighted_text__highlighted_text$46template;
  const highlighted_text__highlighted_value$46template = highlighted_value.highlighted_text__highlighted_value$46template;
  const laminate__components__modal__modal$46template = modal.laminate__components__modal__modal$46template;
  const laminate__enums__alignment$46template = alignment.laminate__enums__alignment$46template;
  const laminate__overlay__module$46template = module.laminate__overlay__module$46template;
  const laminate__popup__module$46template = module$.laminate__popup__module$46template;
  const laminate__popup__popup$46template = popup.laminate__popup__popup$46template;
  const material_button__material_button$46template = material_button.material_button__material_button$46template;
  const material_button__material_button_base$46template = material_button_base.material_button__material_button_base$46template;
  const material_button__material_fab$46template = material_fab.material_button__material_fab$46template;
  const material_checkbox__material_checkbox$46template = material_checkbox.material_checkbox__material_checkbox$46template;
  const material_chips__material_chip$46template = material_chip.material_chips__material_chip$46template;
  const material_chips__material_chips$46template = material_chips.material_chips__material_chips$46template;
  const material_datepicker__calendar$46template = calendar.material_datepicker__calendar$46template;
  const material_datepicker__comparison$46template = comparison.material_datepicker__comparison$46template;
  const material_datepicker__date_input$46template = date_input.material_datepicker__date_input$46template;
  const material_datepicker__date_range_editor$46template = date_range_editor.material_datepicker__date_range_editor$46template;
  const material_datepicker__date_range_input$46template = date_range_input.material_datepicker__date_range_input$46template;
  const material_datepicker__material_calendar_picker$46template = material_calendar_picker.material_datepicker__material_calendar_picker$46template;
  const material_datepicker__material_date_range_picker$46template = material_date_range_picker.material_datepicker__material_date_range_picker$46template;
  const material_datepicker__material_date_time_picker$46template = material_date_time_picker.material_datepicker__material_date_time_picker$46template;
  const material_datepicker__material_datepicker$46template = material_datepicker.material_datepicker__material_datepicker$46template;
  const material_datepicker__material_month_picker$46template = material_month_picker.material_datepicker__material_month_picker$46template;
  const material_datepicker__material_time_picker$46template = material_time_picker.material_datepicker__material_time_picker$46template;
  const material_datepicker__model$46template = model.material_datepicker__model$46template;
  const material_datepicker__module$46template = module$0.material_datepicker__module$46template;
  const material_datepicker__next_prev_buttons$46template = next_prev_buttons.material_datepicker__next_prev_buttons$46template;
  const material_datepicker__preset$46template = preset.material_datepicker__preset$46template;
  const material_dialog__material_dialog$46template = material_dialog.material_dialog__material_dialog$46template;
  const material_expansionpanel__material_expansionpanel$46template = material_expansionpanel.material_expansionpanel__material_expansionpanel$46template;
  const material_expansionpanel__material_expansionpanel_auto_dismiss$46template = material_expansionpanel_auto_dismiss.material_expansionpanel__material_expansionpanel_auto_dismiss$46template;
  const material_expansionpanel__material_expansionpanel_set$46template = material_expansionpanel_set.material_expansionpanel__material_expansionpanel_set$46template;
  const material_icon__material_icon$46template = material_icon.material_icon__material_icon$46template;
  const material_input__base_material_input$46template = base_material_input.material_input__base_material_input$46template;
  const material_input__deferred_validator$46template = deferred_validator.material_input__deferred_validator$46template;
  const material_input__input_wrapper$46template = input_wrapper.material_input__input_wrapper$46template;
  const material_input__material_auto_suggest_input$46template = material_auto_suggest_input.material_input__material_auto_suggest_input$46template;
  const material_input__material_input$46template = material_input.material_input__material_input$46template;
  const material_input__material_input_default_value_accessor$46template = material_input_default_value_accessor.material_input__material_input_default_value_accessor$46template;
  const material_input__material_input_error_keys$46template = material_input_error_keys.material_input__material_input_error_keys$46template;
  const material_input__material_input_multiline$46template = material_input_multiline.material_input__material_input_multiline$46template;
  const material_input__material_number_accessor$46template = material_number_accessor.material_input__material_number_accessor$46template;
  const material_input__material_number_validators$46template = material_number_validators.material_input__material_number_validators$46template;
  const material_input__material_percent_directive$46template = material_percent_directive.material_input__material_percent_directive$46template;
  const material_list__material_list$46template = material_list.material_list__material_list$46template;
  const material_list__material_list_item$46template = material_list_item.material_list__material_list_item$46template;
  const material_list__material_list_size$46template = material_list_size.material_list__material_list_size$46template;
  const material_menu__dropdown_menu$46template = dropdown_menu.material_menu__dropdown_menu$46template;
  const material_menu__material_fab_menu$46template = material_fab_menu.material_menu__material_fab_menu$46template;
  const material_menu__material_menu$46template = material_menu.material_menu__material_menu$46template;
  const material_menu__menu_item_groups$46template = material_menu.material_menu__menu_item_groups$46template;
  const material_menu__menu_popup$46template = material_menu.material_menu__menu_popup$46template;
  const material_menu__menu_item_affix_list$46template = menu_item_affix_list.material_menu__menu_item_affix_list$46template;
  const material_menu__menu_popup_wrapper$46template = menu_popup_wrapper.material_menu__menu_popup_wrapper$46template;
  const material_menu__menu_root$46template = menu_root.material_menu__menu_root$46template;
  const material_popup__material_popup$46template = material_popup.material_popup__material_popup$46template;
  const material_progress__material_progress$46template = material_progress.material_progress__material_progress$46template;
  const material_radio__material_radio$46template = material_radio.material_radio__material_radio$46template;
  const material_radio__material_radio_group$46template = material_radio.material_radio__material_radio_group$46template;
  const material_ripple__material_ripple$46template = material_ripple.material_ripple__material_ripple$46template;
  const material_select__activation_handler$46template = activation_handler.material_select__activation_handler$46template;
  const material_select__display_name$46template = display_name.material_select__display_name$46template;
  const material_select__dropdown_button$46template = dropdown_button.material_select__dropdown_button$46template;
  const material_select__material_dropdown_select$46template = material_dropdown_select.material_select__material_dropdown_select$46template;
  const material_select__material_dropdown_select_accessor$46template = material_dropdown_select_accessor.material_select__material_dropdown_select_accessor$46template;
  const material_select__material_select$46template = material_select.material_select__material_select$46template;
  const material_select__material_select_base$46template = material_select_base.material_select__material_select_base$46template;
  const material_select__material_select_dropdown_item$46template = material_select_dropdown_item.material_select__material_select_dropdown_item$46template;
  const material_select__material_select_item$46template = material_select_item.material_select__material_select_item$46template;
  const material_select__material_select_searchbox$46template = material_select_searchbox.material_select__material_select_searchbox$46template;
  const material_select__shift_click_selection$46template = shift_click_selection.material_select__shift_click_selection$46template;
  const material_spinner__material_spinner$46template = material_spinner.material_spinner__material_spinner$46template;
  const material_tab__fixed_material_tab_strip$46template = fixed_material_tab_strip.material_tab__fixed_material_tab_strip$46template;
  const material_tab__material_tab$46template = material_tab.material_tab__material_tab$46template;
  const material_tab__material_tab_panel$46template = material_tab_panel.material_tab__material_tab_panel$46template;
  const material_tab__tab_button$46template = tab_button.material_tab__tab_button$46template;
  const material_tab__tab_change_event$46template = tab_change_event.material_tab__tab_change_event$46template;
  const material_tab__tab_mixin$46template = tab_mixin.material_tab__tab_mixin$46template;
  const material_toggle__material_toggle$46template = material_toggle.material_toggle__material_toggle$46template;
  const material_tooltip__material_tooltip$46template = material_tooltip.material_tooltip__material_tooltip$46template;
  const material_tooltip__module$46template = module$1.material_tooltip__module$46template;
  const material_tree__material_tree$46template = material_tree.material_tree__material_tree$46template;
  const material_yes_no_buttons__material_yes_no_buttons$46template = material_yes_no_buttons.material_yes_no_buttons__material_yes_no_buttons$46template;
  const mixins__button_wrapper$46template = button_wrapper.mixins__button_wrapper$46template;
  const mixins__focusable_mixin$46template = focusable_mixin.mixins__focusable_mixin$46template;
  const mixins__has_tab_index$46template = has_tab_index.mixins__has_tab_index$46template;
  const mixins__highlight_assistant_mixin$46template = highlight_assistant_mixin.mixins__highlight_assistant_mixin$46template;
  const mixins__material_dropdown_base$46template = material_dropdown_base.mixins__material_dropdown_base$46template;
  const mixins__track_layout_changes$46template = track_layout_changes.mixins__track_layout_changes$46template;
  const model__date__date$46template = date.model__date__date$46template;
  const model__selection__select$46template = select.model__selection__select$46template;
  const model__selection__selection_model$46template = selection_model.model__selection__selection_model$46template;
  const model__selection__selection_options$46template = selection_options.model__selection__selection_options$46template;
  const model__selection__string_selection_options$46template = string_selection_options.model__selection__string_selection_options$46template;
  const model__ui__display_name$46template = display_name$.model__ui__display_name$46template;
  const model__ui__has_renderer$46template = has_renderer.model__ui__has_renderer$46template;
  const model__ui__icon$46template = icon.model__ui__icon$46template;
  const reorder_list__reorder_events$46template = reorder_events.reorder_list__reorder_events$46template;
  const reorder_list__reorder_list$46template = reorder_list.reorder_list__reorder_list$46template;
  const scorecard__scoreboard$46template = scoreboard.scorecard__scoreboard$46template;
  const scorecard__scorecard$46template = scorecard.scorecard__scorecard$46template;
  const stop_propagation__stop_propagation$46template = stop_propagation.stop_propagation__stop_propagation$46template;
  const theme__dark_theme$46template = dark_theme.theme__dark_theme$46template;
  const theme__module$46template = module$2.theme__module$46template;
  const utils__async__async$46template = async.utils__async__async$46template;
  const _root = Object.create(null);
  const angular_components$46template = Object.create(_root);
  let VoidTovoid = () => (VoidTovoid = dart.constFn(dart.fnType(dart.void, [])))();
  dart.defineLazy(angular_components$46template, {
    /*angular_components$46template._visited*/get _visited() {
      return false;
    },
    set _visited(_) {}
  });
  angular_components$46template.initReflector = function() {
    if (dart.test(angular_components$46template._visited)) {
      return;
    }
    angular_components$46template._visited = true;
    annotations__rtl_annotation$46template.initReflector();
    app_layout__material_drawer_base$46template.initReflector();
    app_layout__material_persistent_drawer$46template.initReflector();
    app_layout__material_persistent_drawer$46template.initReflector();
    app_layout__material_temporary_drawer$46template.initReflector();
    app_layout__material_temporary_drawer$46template.initReflector();
    auto_dismiss__auto_dismiss$46template.initReflector();
    auto_dismiss__auto_dismiss$46template.initReflector();
    button_decorator__button_decorator$46template.initReflector();
    button_decorator__button_decorator$46template.initReflector();
    content__deferred_content$46template.initReflector();
    content__deferred_content$46template.initReflector();
    content__deferred_content_aware$46template.initReflector();
    dynamic_component__dynamic_component$46template.initReflector();
    dynamic_component__dynamic_component$46template.initReflector();
    focus__focus$46template.initReflector();
    focus__focus$46template.initReflector();
    focus__focus_activable_item$46template.initReflector();
    focus__focus_activable_item$46template.initReflector();
    focus__focus_item$46template.initReflector();
    focus__focus_item$46template.initReflector();
    focus__focus_list$46template.initReflector();
    focus__focus_list$46template.initReflector();
    focus__focus_trap$46template.initReflector();
    focus__focus_trap$46template.initReflector();
    focus__keyboard_only_focus_indicator$46template.initReflector();
    focus__keyboard_only_focus_indicator$46template.initReflector();
    forms__error_renderer$46template.initReflector();
    glyph__glyph$46template.initReflector();
    glyph__glyph$46template.initReflector();
    highlighted_text__highlighted_text$46template.initReflector();
    highlighted_text__highlighted_text$46template.initReflector();
    highlighted_text__highlighted_value$46template.initReflector();
    highlighted_text__highlighted_value$46template.initReflector();
    laminate__components__modal__modal$46template.initReflector();
    laminate__components__modal__modal$46template.initReflector();
    laminate__enums__alignment$46template.initReflector();
    laminate__overlay__module$46template.initReflector();
    laminate__popup__module$46template.initReflector();
    laminate__popup__popup$46template.initReflector();
    laminate__popup__popup$46template.initReflector();
    material_button__material_button$46template.initReflector();
    material_button__material_button$46template.initReflector();
    material_button__material_button_base$46template.initReflector();
    material_button__material_fab$46template.initReflector();
    material_button__material_fab$46template.initReflector();
    material_checkbox__material_checkbox$46template.initReflector();
    material_checkbox__material_checkbox$46template.initReflector();
    material_chips__material_chip$46template.initReflector();
    material_chips__material_chip$46template.initReflector();
    material_chips__material_chips$46template.initReflector();
    material_chips__material_chips$46template.initReflector();
    material_datepicker__calendar$46template.initReflector();
    material_datepicker__comparison$46template.initReflector();
    material_datepicker__date_input$46template.initReflector();
    material_datepicker__date_input$46template.initReflector();
    material_datepicker__date_range_editor$46template.initReflector();
    material_datepicker__date_range_editor$46template.initReflector();
    material_datepicker__date_range_input$46template.initReflector();
    material_datepicker__date_range_input$46template.initReflector();
    material_datepicker__material_calendar_picker$46template.initReflector();
    material_datepicker__material_calendar_picker$46template.initReflector();
    material_datepicker__material_date_range_picker$46template.initReflector();
    material_datepicker__material_date_range_picker$46template.initReflector();
    material_datepicker__material_date_time_picker$46template.initReflector();
    material_datepicker__material_date_time_picker$46template.initReflector();
    material_datepicker__material_datepicker$46template.initReflector();
    material_datepicker__material_datepicker$46template.initReflector();
    material_datepicker__material_month_picker$46template.initReflector();
    material_datepicker__material_month_picker$46template.initReflector();
    material_datepicker__material_time_picker$46template.initReflector();
    material_datepicker__material_time_picker$46template.initReflector();
    material_datepicker__model$46template.initReflector();
    material_datepicker__module$46template.initReflector();
    material_datepicker__module$46template.initReflector();
    material_datepicker__next_prev_buttons$46template.initReflector();
    material_datepicker__preset$46template.initReflector();
    material_dialog__material_dialog$46template.initReflector();
    material_dialog__material_dialog$46template.initReflector();
    material_expansionpanel__material_expansionpanel$46template.initReflector();
    material_expansionpanel__material_expansionpanel$46template.initReflector();
    material_expansionpanel__material_expansionpanel_auto_dismiss$46template.initReflector();
    material_expansionpanel__material_expansionpanel_auto_dismiss$46template.initReflector();
    material_expansionpanel__material_expansionpanel_set$46template.initReflector();
    material_expansionpanel__material_expansionpanel_set$46template.initReflector();
    material_icon__material_icon$46template.initReflector();
    material_icon__material_icon$46template.initReflector();
    material_input__base_material_input$46template.initReflector();
    material_input__deferred_validator$46template.initReflector();
    material_input__input_wrapper$46template.initReflector();
    material_input__material_auto_suggest_input$46template.initReflector();
    material_input__material_auto_suggest_input$46template.initReflector();
    material_input__material_input$46template.initReflector();
    material_input__material_input$46template.initReflector();
    material_input__material_input_default_value_accessor$46template.initReflector();
    material_input__material_input_default_value_accessor$46template.initReflector();
    material_input__material_input_error_keys$46template.initReflector();
    material_input__material_input_multiline$46template.initReflector();
    material_input__material_input_multiline$46template.initReflector();
    material_input__material_number_accessor$46template.initReflector();
    material_input__material_number_accessor$46template.initReflector();
    material_input__material_number_validators$46template.initReflector();
    material_input__material_number_validators$46template.initReflector();
    material_input__material_percent_directive$46template.initReflector();
    material_input__material_percent_directive$46template.initReflector();
    material_list__material_list$46template.initReflector();
    material_list__material_list$46template.initReflector();
    material_list__material_list_item$46template.initReflector();
    material_list__material_list_item$46template.initReflector();
    material_list__material_list_size$46template.initReflector();
    material_menu__dropdown_menu$46template.initReflector();
    material_menu__dropdown_menu$46template.initReflector();
    material_menu__material_fab_menu$46template.initReflector();
    material_menu__material_fab_menu$46template.initReflector();
    material_menu__material_menu$46template.initReflector();
    material_menu__material_menu$46template.initReflector();
    material_menu__menu_item_affix_list$46template.initReflector();
    material_menu__menu_item_affix_list$46template.initReflector();
    material_menu__menu_item_groups$46template.initReflector();
    material_menu__menu_item_groups$46template.initReflector();
    material_menu__menu_popup$46template.initReflector();
    material_menu__menu_popup$46template.initReflector();
    material_menu__menu_popup_wrapper$46template.initReflector();
    material_menu__menu_root$46template.initReflector();
    material_popup__material_popup$46template.initReflector();
    material_popup__material_popup$46template.initReflector();
    material_progress__material_progress$46template.initReflector();
    material_progress__material_progress$46template.initReflector();
    material_radio__material_radio$46template.initReflector();
    material_radio__material_radio$46template.initReflector();
    material_radio__material_radio_group$46template.initReflector();
    material_radio__material_radio_group$46template.initReflector();
    material_ripple__material_ripple$46template.initReflector();
    material_ripple__material_ripple$46template.initReflector();
    material_select__activation_handler$46template.initReflector();
    material_select__display_name$46template.initReflector();
    material_select__display_name$46template.initReflector();
    material_select__dropdown_button$46template.initReflector();
    material_select__dropdown_button$46template.initReflector();
    material_select__material_dropdown_select$46template.initReflector();
    material_select__material_dropdown_select$46template.initReflector();
    material_select__material_dropdown_select_accessor$46template.initReflector();
    material_select__material_dropdown_select_accessor$46template.initReflector();
    material_select__material_select$46template.initReflector();
    material_select__material_select$46template.initReflector();
    material_select__material_select_base$46template.initReflector();
    material_select__material_select_dropdown_item$46template.initReflector();
    material_select__material_select_dropdown_item$46template.initReflector();
    material_select__material_select_item$46template.initReflector();
    material_select__material_select_item$46template.initReflector();
    material_select__material_select_searchbox$46template.initReflector();
    material_select__material_select_searchbox$46template.initReflector();
    material_select__shift_click_selection$46template.initReflector();
    material_spinner__material_spinner$46template.initReflector();
    material_spinner__material_spinner$46template.initReflector();
    material_tab__fixed_material_tab_strip$46template.initReflector();
    material_tab__fixed_material_tab_strip$46template.initReflector();
    material_tab__material_tab$46template.initReflector();
    material_tab__material_tab$46template.initReflector();
    material_tab__material_tab_panel$46template.initReflector();
    material_tab__material_tab_panel$46template.initReflector();
    material_tab__tab_button$46template.initReflector();
    material_tab__tab_button$46template.initReflector();
    material_tab__tab_change_event$46template.initReflector();
    material_tab__tab_mixin$46template.initReflector();
    material_toggle__material_toggle$46template.initReflector();
    material_toggle__material_toggle$46template.initReflector();
    material_tooltip__material_tooltip$46template.initReflector();
    material_tooltip__material_tooltip$46template.initReflector();
    material_tooltip__module$46template.initReflector();
    material_tree__material_tree$46template.initReflector();
    material_tree__material_tree$46template.initReflector();
    material_yes_no_buttons__material_yes_no_buttons$46template.initReflector();
    material_yes_no_buttons__material_yes_no_buttons$46template.initReflector();
    mixins__button_wrapper$46template.initReflector();
    mixins__focusable_mixin$46template.initReflector();
    mixins__has_tab_index$46template.initReflector();
    mixins__highlight_assistant_mixin$46template.initReflector();
    mixins__material_dropdown_base$46template.initReflector();
    mixins__track_layout_changes$46template.initReflector();
    model__date__date$46template.initReflector();
    model__selection__select$46template.initReflector();
    model__selection__selection_model$46template.initReflector();
    model__selection__selection_options$46template.initReflector();
    model__selection__string_selection_options$46template.initReflector();
    model__ui__display_name$46template.initReflector();
    model__ui__has_renderer$46template.initReflector();
    model__ui__icon$46template.initReflector();
    reorder_list__reorder_events$46template.initReflector();
    reorder_list__reorder_list$46template.initReflector();
    reorder_list__reorder_list$46template.initReflector();
    scorecard__scoreboard$46template.initReflector();
    scorecard__scoreboard$46template.initReflector();
    scorecard__scorecard$46template.initReflector();
    scorecard__scorecard$46template.initReflector();
    stop_propagation__stop_propagation$46template.initReflector();
    stop_propagation__stop_propagation$46template.initReflector();
    theme__dark_theme$46template.initReflector();
    theme__dark_theme$46template.initReflector();
    theme__module$46template.initReflector();
    utils__async__async$46template.initReflector();
  };
  dart.fn(angular_components$46template.initReflector, VoidTovoid());
  dart.trackLibraries("packages/angular_components/angular_components.template.ddc", {
    "package:angular_components/angular_components.template.dart": angular_components$46template
  }, '{"version":3,"sourceRoot":"","sources":["angular_components.template.dart"],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;MAiSI,sCAAQ;YAAG;;;;;AAEb,kBAAI,sCAAQ,GAAE;AACZ;;AAEF,6CAAW;AAEX,IAAM,oDAAa;AACnB,IAAM,yDAAa;AACnB,IAAM,+DAAa;AACnB,IAAM,+DAAa;AACnB,IAAM,8DAAa;AACnB,IAAM,8DAAa;AACnB,IAAM,mDAAa;AACnB,IAAM,mDAAa;AACnB,IAAM,2DAAa;AACnB,IAAM,2DAAa;AACnB,IAAO,kDAAa;AACpB,IAAO,kDAAa;AACpB,IAAO,wDAAa;AACpB,IAAO,6DAAa;AACpB,IAAO,6DAAa;AACpB,IAAO,qCAAa;AACpB,IAAO,qCAAa;AACpB,IAAO,oDAAa;AACpB,IAAO,oDAAa;AACpB,IAAO,0CAAa;AACpB,IAAO,0CAAa;AACpB,IAAO,0CAAa;AACpB,IAAO,0CAAa;AACpB,IAAO,0CAAa;AACpB,IAAO,0CAAa;AACpB,IAAO,6DAAa;AACpB,IAAO,6DAAa;AACpB,IAAO,8CAAa;AACpB,IAAO,qCAAa;AACpB,IAAO,qCAAa;AACpB,IAAO,2DAAa;AACpB,IAAO,2DAAa;AACpB,IAAO,4DAAa;AACpB,IAAO,4DAAa;AACpB,IAAO,2DAAa;AACpB,IAAO,2DAAa;AACpB,IAAO,mDAAa;AACpB,IAAO,kDAAa;AACpB,IAAO,gDAAa;AACpB,IAAO,+CAAa;AACpB,IAAO,+CAAa;AACpB,IAAO,yDAAa;AACpB,IAAO,yDAAa;AACpB,IAAO,8DAAa;AACpB,IAAO,sDAAa;AACpB,IAAO,sDAAa;AACpB,IAAO,6DAAa;AACpB,IAAO,6DAAa;AACpB,IAAO,sDAAa;AACpB,IAAO,sDAAa;AACpB,IAAO,uDAAa;AACpB,IAAO,uDAAa;AACpB,IAAO,sDAAa;AACpB,IAAO,wDAAa;AACpB,IAAO,wDAAa;AACpB,IAAO,wDAAa;AACpB,IAAO,+DAAa;AACpB,IAAO,+DAAa;AACpB,IAAO,8DAAa;AACpB,IAAO,8DAAa;AACpB,IAAO,sEAAa;AACpB,IAAO,sEAAa;AACpB,IAAO,wEAAa;AACpB,IAAO,wEAAa;AACpB,IAAO,uEAAa;AACpB,IAAO,uEAAa;AACpB,IAAO,iEAAa;AACpB,IAAO,iEAAa;AACpB,IAAO,mEAAa;AACpB,IAAO,mEAAa;AACpB,IAAO,kEAAa;AACpB,IAAO,kEAAa;AACpB,IAAO,mDAAa;AACpB,IAAO,oDAAa;AACpB,IAAO,oDAAa;AACpB,IAAO,+DAAa;AACpB,IAAO,oDAAa;AACpB,IAAO,yDAAa;AACpB,IAAO,yDAAa;AACpB,IAAO,yEAAa;AACpB,IAAO,yEAAa;AACpB,IAAO,sFAAa;AACpB,IAAO,sFAAa;AACpB,IAAO,6EAAa;AACpB,IAAO,6EAAa;AACpB,IAAO,qDAAa;AACpB,IAAO,qDAAa;AACpB,IAAO,4DAAa;AACpB,IAAO,2DAAa;AACpB,IAAO,sDAAa;AACpB,IAAO,oEAAa;AACpB,IAAO,oEAAa;AACpB,IAAO,uDAAa;AACpB,IAAO,uDAAa;AACpB,IAAO,8EAAa;AACpB,IAAO,8EAAa;AACpB,IAAO,kEAAa;AACpB,IAAO,iEAAa;AACpB,IAAO,iEAAa;AACpB,IAAO,iEAAa;AACpB,IAAQ,iEAAa;AACrB,IAAQ,mEAAa;AACrB,IAAQ,mEAAa;AACrB,IAAQ,mEAAa;AACrB,IAAQ,mEAAa;AACrB,IAAQ,qDAAa;AACrB,IAAQ,qDAAa;AACrB,IAAQ,0DAAa;AACrB,IAAQ,0DAAa;AACrB,IAAQ,0DAAa;AACrB,IAAQ,qDAAa;AACrB,IAAQ,qDAAa;AACrB,IAAQ,yDAAa;AACrB,IAAQ,yDAAa;AACrB,IAAQ,qDAAa;AACrB,IAAQ,qDAAa;AACrB,IAAQ,4DAAa;AACrB,IAAQ,4DAAa;AACrB,IAAQ,wDAAa;AACrB,IAAQ,wDAAa;AACrB,IAAQ,kDAAa;AACrB,IAAQ,kDAAa;AACrB,IAAQ,0DAAa;AACrB,IAAQ,iDAAa;AACrB,IAAQ,uDAAa;AACrB,IAAQ,uDAAa;AACrB,IAAQ,6DAAa;AACrB,IAAQ,6DAAa;AACrB,IAAQ,uDAAa;AACrB,IAAQ,uDAAa;AACrB,IAAQ,6DAAa;AACrB,IAAQ,6DAAa;AACrB,IAAQ,yDAAa;AACrB,IAAQ,yDAAa;AACrB,IAAQ,4DAAa;AACrB,IAAQ,sDAAa;AACrB,IAAQ,sDAAa;AACrB,IAAQ,yDAAa;AACrB,IAAQ,yDAAa;AACrB,IAAQ,kEAAa;AACrB,IAAQ,kEAAa;AACrB,IAAQ,2EAAa;AACrB,IAAQ,2EAAa;AACrB,IAAQ,yDAAa;AACrB,IAAQ,yDAAa;AACrB,IAAQ,8DAAa;AACrB,IAAQ,uEAAa;AACrB,IAAQ,uEAAa;AACrB,IAAQ,8DAAa;AACrB,IAAQ,8DAAa;AACrB,IAAQ,mEAAa;AACrB,IAAQ,mEAAa;AACrB,IAAQ,+DAAa;AACrB,IAAQ,2DAAa;AACrB,IAAQ,2DAAa;AACrB,IAAQ,+DAAa;AACrB,IAAQ,+DAAa;AACrB,IAAQ,mDAAa;AACrB,IAAQ,mDAAa;AACrB,IAAQ,yDAAa;AACrB,IAAQ,yDAAa;AACrB,IAAQ,iDAAa;AACrB,IAAQ,iDAAa;AACrB,IAAQ,uDAAa;AACrB,IAAQ,gDAAa;AACrB,IAAQ,yDAAa;AACrB,IAAQ,yDAAa;AACrB,IAAQ,2DAAa;AACrB,IAAQ,2DAAa;AACrB,IAAQ,iDAAa;AACrB,IAAQ,qDAAa;AACrB,IAAQ,qDAAa;AACrB,IAAQ,yEAAa;AACrB,IAAQ,yEAAa;AACrB,IAAQ,+CAAa;AACrB,IAAQ,gDAAa;AACrB,IAAQ,8CAAa;AACrB,IAAQ,0DAAa;AACrB,IAAQ,uDAAa;AACrB,IAAQ,qDAAa;AACrB,IAAQ,0CAAa;AACrB,IAAQ,iDAAa;AACrB,IAAQ,0DAAa;AACrB,IAAQ,4DAAa;AACrB,IAAQ,mEAAa;AACrB,IAAQ,gDAAa;AACrB,IAAQ,gDAAa;AACrB,IAAQ,wCAAa;AACrB,IAAQ,qDAAa;AACrB,IAAQ,mDAAa;AACrB,IAAQ,mDAAa;AACrB,IAAQ,8CAAa;AACrB,IAAQ,8CAAa;AACrB,IAAQ,6CAAa;AACrB,IAAQ,6CAAa;AACrB,IAAQ,2DAAa;AACrB,IAAQ,2DAAa;AACrB,IAAQ,0CAAa;AACrB,IAAQ,0CAAa;AACrB,IAAQ,sCAAa;AACrB,IAAQ,4CAAa;EACvB","file":"angular_components.template.ddc.js"}');
  // Exports:
  return {
    angular_components$46template: angular_components$46template
  };
});

//# sourceMappingURL=angular_components.template.ddc.js.map
