// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Generator: TemplateGenerator
// **************************************************************************

// ignore_for_file: cancel_subscriptions,constant_identifier_names,duplicate_import,non_constant_identifier_names,library_prefixes,UNUSED_IMPORT,UNUSED_SHOWN_NAME
import 'angular_components.dart';
export 'angular_components.dart';
import 'package:angular/angular.dart' show Provider;
import 'app_layout/material_persistent_drawer.dart';
import 'app_layout/material_temporary_drawer.dart';
import 'auto_dismiss/auto_dismiss.dart';
import 'button_decorator/button_decorator.dart';
import 'content/deferred_content.dart';
import 'dynamic_component/dynamic_component.dart';
import 'focus/focus.dart';
import 'focus/focus_activable_item.dart';
import 'focus/focus_item.dart';
import 'focus/focus_list.dart';
import 'focus/focus_trap.dart';
import 'focus/keyboard_only_focus_indicator.dart';
import 'glyph/glyph.dart';
import 'highlighted_text/highlighted_text.dart';
import 'highlighted_text/highlighted_value.dart';
import 'laminate/components/modal/modal.dart';
import 'laminate/popup/module.dart';
import 'laminate/popup/popup.dart';
import 'material_button/material_button.dart';
import 'material_button/material_fab.dart';
import 'material_checkbox/material_checkbox.dart' show MaterialCheckboxComponent;
import 'material_chips/material_chip.dart';
import 'material_chips/material_chips.dart';
import 'material_dialog/material_dialog.dart';
import 'material_expansionpanel/material_expansionpanel.dart';
import 'material_expansionpanel/material_expansionpanel_auto_dismiss.dart';
import 'material_expansionpanel/material_expansionpanel_set.dart';
import 'material_icon/material_icon.dart';
import 'material_input/material_auto_suggest_input.dart';
import 'material_input/material_input.dart' hide materialInputErrorKey;
import 'material_input/material_input_default_value_accessor.dart';
import 'material_input/material_input_multiline.dart';
import 'material_input/material_number_accessor.dart';
import 'material_input/material_number_validators.dart';
import 'material_input/material_percent_directive.dart';
import 'material_list/material_list.dart';
import 'material_list/material_list_item.dart';
import 'material_menu/dropdown_menu.dart';
import 'material_menu/material_fab_menu.dart';
import 'material_menu/material_menu.dart';
import 'material_menu/menu_item_affix_list.dart';
import 'material_menu/menu_item_groups.dart';
import 'material_menu/menu_popup.dart';
import 'material_menu/menu_root.dart';
import 'material_popup/material_popup.dart';
import 'material_progress/material_progress.dart';
import 'material_radio/material_radio.dart';
import 'material_radio/material_radio_group.dart';
import 'material_ripple/material_ripple.dart';
import 'material_select/display_name.dart';
import 'material_select/dropdown_button.dart';
import 'material_select/material_dropdown_select.dart';
import 'material_select/material_select.dart';
import 'material_select/material_select_dropdown_item.dart';
import 'material_select/material_select_item.dart';
import 'material_select/material_select_searchbox.dart';
import 'material_spinner/material_spinner.dart';
import 'material_tab/fixed_material_tab_strip.dart';
import 'material_tab/material_tab.dart';
import 'material_tab/material_tab_panel.dart';
import 'material_tab/tab_button.dart';
import 'material_toggle/material_toggle.dart';
import 'material_tooltip/material_tooltip.dart';
import 'material_tree/material_tree.dart';
import 'material_yes_no_buttons/material_yes_no_buttons.dart';
import 'reorder_list/reorder_list.dart';
import 'scorecard/scoreboard.dart';
import 'scorecard/scorecard.dart';
import 'stop_propagation/stop_propagation.dart';
import 'theme/dark_theme.dart';
// Required for initReflector().
import 'annotations/rtl_annotation.template.dart' as _ref0;
import 'app_layout/material_drawer_base.template.dart' as _ref1;
import 'app_layout/material_persistent_drawer.template.dart' as _ref2;
import 'app_layout/material_persistent_drawer.template.dart' as _ref3;
import 'app_layout/material_temporary_drawer.template.dart' as _ref4;
import 'app_layout/material_temporary_drawer.template.dart' as _ref5;
import 'auto_dismiss/auto_dismiss.template.dart' as _ref6;
import 'auto_dismiss/auto_dismiss.template.dart' as _ref7;
import 'button_decorator/button_decorator.template.dart' as _ref8;
import 'button_decorator/button_decorator.template.dart' as _ref9;
import 'content/deferred_content.template.dart' as _ref10;
import 'content/deferred_content.template.dart' as _ref11;
import 'content/deferred_content_aware.template.dart' as _ref12;
import 'dynamic_component/dynamic_component.template.dart' as _ref13;
import 'dynamic_component/dynamic_component.template.dart' as _ref14;
import 'focus/focus.template.dart' as _ref15;
import 'focus/focus.template.dart' as _ref16;
import 'focus/focus_activable_item.template.dart' as _ref17;
import 'focus/focus_activable_item.template.dart' as _ref18;
import 'focus/focus_item.template.dart' as _ref19;
import 'focus/focus_item.template.dart' as _ref20;
import 'focus/focus_list.template.dart' as _ref21;
import 'focus/focus_list.template.dart' as _ref22;
import 'focus/focus_trap.template.dart' as _ref23;
import 'focus/focus_trap.template.dart' as _ref24;
import 'focus/keyboard_only_focus_indicator.template.dart' as _ref25;
import 'focus/keyboard_only_focus_indicator.template.dart' as _ref26;
import 'forms/error_renderer.template.dart' as _ref27;
import 'glyph/glyph.template.dart' as _ref28;
import 'glyph/glyph.template.dart' as _ref29;
import 'highlighted_text/highlighted_text.template.dart' as _ref30;
import 'highlighted_text/highlighted_text.template.dart' as _ref31;
import 'highlighted_text/highlighted_value.template.dart' as _ref32;
import 'highlighted_text/highlighted_value.template.dart' as _ref33;
import 'laminate/components/modal/modal.template.dart' as _ref34;
import 'laminate/components/modal/modal.template.dart' as _ref35;
import 'laminate/enums/alignment.template.dart' as _ref36;
import 'laminate/overlay/module.template.dart' as _ref37;
import 'laminate/popup/module.template.dart' as _ref38;
import 'laminate/popup/module.template.dart' as _ref39;
import 'laminate/popup/popup.template.dart' as _ref40;
import 'laminate/popup/popup.template.dart' as _ref41;
import 'material_button/material_button.template.dart' as _ref42;
import 'material_button/material_button.template.dart' as _ref43;
import 'material_button/material_button_base.template.dart' as _ref44;
import 'material_button/material_fab.template.dart' as _ref45;
import 'material_button/material_fab.template.dart' as _ref46;
import 'material_checkbox/material_checkbox.template.dart' as _ref47;
import 'material_checkbox/material_checkbox.template.dart' as _ref48;
import 'material_chips/material_chip.template.dart' as _ref49;
import 'material_chips/material_chip.template.dart' as _ref50;
import 'material_chips/material_chips.template.dart' as _ref51;
import 'material_chips/material_chips.template.dart' as _ref52;
import 'material_dialog/material_dialog.template.dart' as _ref53;
import 'material_dialog/material_dialog.template.dart' as _ref54;
import 'material_expansionpanel/material_expansionpanel.template.dart' as _ref55;
import 'material_expansionpanel/material_expansionpanel.template.dart' as _ref56;
import 'material_expansionpanel/material_expansionpanel_auto_dismiss.template.dart' as _ref57;
import 'material_expansionpanel/material_expansionpanel_auto_dismiss.template.dart' as _ref58;
import 'material_expansionpanel/material_expansionpanel_set.template.dart' as _ref59;
import 'material_expansionpanel/material_expansionpanel_set.template.dart' as _ref60;
import 'material_icon/material_icon.template.dart' as _ref61;
import 'material_icon/material_icon.template.dart' as _ref62;
import 'material_input/base_material_input.template.dart' as _ref63;
import 'material_input/deferred_validator.template.dart' as _ref64;
import 'material_input/input_wrapper.template.dart' as _ref65;
import 'material_input/material_auto_suggest_input.template.dart' as _ref66;
import 'material_input/material_auto_suggest_input.template.dart' as _ref67;
import 'material_input/material_input.template.dart' as _ref68;
import 'material_input/material_input.template.dart' as _ref69;
import 'material_input/material_input_default_value_accessor.template.dart' as _ref70;
import 'material_input/material_input_default_value_accessor.template.dart' as _ref71;
import 'material_input/material_input_error_keys.template.dart' as _ref72;
import 'material_input/material_input_multiline.template.dart' as _ref73;
import 'material_input/material_input_multiline.template.dart' as _ref74;
import 'material_input/material_number_accessor.template.dart' as _ref75;
import 'material_input/material_number_accessor.template.dart' as _ref76;
import 'material_input/material_number_validators.template.dart' as _ref77;
import 'material_input/material_number_validators.template.dart' as _ref78;
import 'material_input/material_percent_directive.template.dart' as _ref79;
import 'material_input/material_percent_directive.template.dart' as _ref80;
import 'material_list/material_list.template.dart' as _ref81;
import 'material_list/material_list.template.dart' as _ref82;
import 'material_list/material_list_item.template.dart' as _ref83;
import 'material_list/material_list_item.template.dart' as _ref84;
import 'material_list/material_list_size.template.dart' as _ref85;
import 'material_menu/dropdown_menu.template.dart' as _ref86;
import 'material_menu/dropdown_menu.template.dart' as _ref87;
import 'material_menu/material_fab_menu.template.dart' as _ref88;
import 'material_menu/material_fab_menu.template.dart' as _ref89;
import 'material_menu/material_menu.template.dart' as _ref90;
import 'material_menu/material_menu.template.dart' as _ref91;
import 'material_menu/menu_item_affix_list.template.dart' as _ref92;
import 'material_menu/menu_item_affix_list.template.dart' as _ref93;
import 'material_menu/menu_item_groups.template.dart' as _ref94;
import 'material_menu/menu_item_groups.template.dart' as _ref95;
import 'material_menu/menu_popup.template.dart' as _ref96;
import 'material_menu/menu_popup.template.dart' as _ref97;
import 'material_menu/menu_popup_wrapper.template.dart' as _ref98;
import 'material_menu/menu_root.template.dart' as _ref99;
import 'material_popup/material_popup.template.dart' as _ref100;
import 'material_popup/material_popup.template.dart' as _ref101;
import 'material_progress/material_progress.template.dart' as _ref102;
import 'material_progress/material_progress.template.dart' as _ref103;
import 'material_radio/material_radio.template.dart' as _ref104;
import 'material_radio/material_radio.template.dart' as _ref105;
import 'material_radio/material_radio_group.template.dart' as _ref106;
import 'material_radio/material_radio_group.template.dart' as _ref107;
import 'material_ripple/material_ripple.template.dart' as _ref108;
import 'material_ripple/material_ripple.template.dart' as _ref109;
import 'material_select/activation_handler.template.dart' as _ref110;
import 'material_select/display_name.template.dart' as _ref111;
import 'material_select/display_name.template.dart' as _ref112;
import 'material_select/dropdown_button.template.dart' as _ref113;
import 'material_select/dropdown_button.template.dart' as _ref114;
import 'material_select/material_dropdown_select.template.dart' as _ref115;
import 'material_select/material_dropdown_select.template.dart' as _ref116;
import 'material_select/material_select.template.dart' as _ref117;
import 'material_select/material_select.template.dart' as _ref118;
import 'material_select/material_select_base.template.dart' as _ref119;
import 'material_select/material_select_dropdown_item.template.dart' as _ref120;
import 'material_select/material_select_dropdown_item.template.dart' as _ref121;
import 'material_select/material_select_item.template.dart' as _ref122;
import 'material_select/material_select_item.template.dart' as _ref123;
import 'material_select/material_select_searchbox.template.dart' as _ref124;
import 'material_select/material_select_searchbox.template.dart' as _ref125;
import 'material_select/shift_click_selection.template.dart' as _ref126;
import 'material_spinner/material_spinner.template.dart' as _ref127;
import 'material_spinner/material_spinner.template.dart' as _ref128;
import 'material_tab/fixed_material_tab_strip.template.dart' as _ref129;
import 'material_tab/fixed_material_tab_strip.template.dart' as _ref130;
import 'material_tab/material_tab.template.dart' as _ref131;
import 'material_tab/material_tab.template.dart' as _ref132;
import 'material_tab/material_tab_panel.template.dart' as _ref133;
import 'material_tab/material_tab_panel.template.dart' as _ref134;
import 'material_tab/tab_button.template.dart' as _ref135;
import 'material_tab/tab_button.template.dart' as _ref136;
import 'material_tab/tab_change_event.template.dart' as _ref137;
import 'material_tab/tab_mixin.template.dart' as _ref138;
import 'material_toggle/material_toggle.template.dart' as _ref139;
import 'material_toggle/material_toggle.template.dart' as _ref140;
import 'material_tooltip/material_tooltip.template.dart' as _ref141;
import 'material_tooltip/material_tooltip.template.dart' as _ref142;
import 'material_tooltip/module.template.dart' as _ref143;
import 'material_tree/material_tree.template.dart' as _ref144;
import 'material_tree/material_tree.template.dart' as _ref145;
import 'material_yes_no_buttons/material_yes_no_buttons.template.dart' as _ref146;
import 'material_yes_no_buttons/material_yes_no_buttons.template.dart' as _ref147;
import 'mixins/button_wrapper.template.dart' as _ref148;
import 'mixins/focusable_mixin.template.dart' as _ref149;
import 'mixins/has_tab_index.template.dart' as _ref150;
import 'mixins/highlight_assistant_mixin.template.dart' as _ref151;
import 'mixins/material_dropdown_base.template.dart' as _ref152;
import 'mixins/track_layout_changes.template.dart' as _ref153;
import 'model/selection/select.template.dart' as _ref154;
import 'model/selection/selection_model.template.dart' as _ref155;
import 'model/selection/selection_options.template.dart' as _ref156;
import 'model/selection/string_selection_options.template.dart' as _ref157;
import 'model/ui/display_name.template.dart' as _ref158;
import 'model/ui/has_renderer.template.dart' as _ref159;
import 'model/ui/icon.template.dart' as _ref160;
import 'package:angular/angular.template.dart' as _ref161;
import 'reorder_list/reorder_events.template.dart' as _ref162;
import 'reorder_list/reorder_list.template.dart' as _ref163;
import 'reorder_list/reorder_list.template.dart' as _ref164;
import 'scorecard/scoreboard.template.dart' as _ref165;
import 'scorecard/scoreboard.template.dart' as _ref166;
import 'scorecard/scorecard.template.dart' as _ref167;
import 'scorecard/scorecard.template.dart' as _ref168;
import 'stop_propagation/stop_propagation.template.dart' as _ref169;
import 'stop_propagation/stop_propagation.template.dart' as _ref170;
import 'theme/dark_theme.template.dart' as _ref171;
import 'theme/dark_theme.template.dart' as _ref172;
import 'theme/module.template.dart' as _ref173;
import 'utils/async/async.template.dart' as _ref174;

var _visited = false;
void initReflector() {
  if (_visited) {
    return;
  }
  _visited = true;
  _ref0.initReflector();
  _ref1.initReflector();
  _ref2.initReflector();
  _ref3.initReflector();
  _ref4.initReflector();
  _ref5.initReflector();
  _ref6.initReflector();
  _ref7.initReflector();
  _ref8.initReflector();
  _ref9.initReflector();
  _ref10.initReflector();
  _ref11.initReflector();
  _ref12.initReflector();
  _ref13.initReflector();
  _ref14.initReflector();
  _ref15.initReflector();
  _ref16.initReflector();
  _ref17.initReflector();
  _ref18.initReflector();
  _ref19.initReflector();
  _ref20.initReflector();
  _ref21.initReflector();
  _ref22.initReflector();
  _ref23.initReflector();
  _ref24.initReflector();
  _ref25.initReflector();
  _ref26.initReflector();
  _ref27.initReflector();
  _ref28.initReflector();
  _ref29.initReflector();
  _ref30.initReflector();
  _ref31.initReflector();
  _ref32.initReflector();
  _ref33.initReflector();
  _ref34.initReflector();
  _ref35.initReflector();
  _ref36.initReflector();
  _ref37.initReflector();
  _ref38.initReflector();
  _ref39.initReflector();
  _ref40.initReflector();
  _ref41.initReflector();
  _ref42.initReflector();
  _ref43.initReflector();
  _ref44.initReflector();
  _ref45.initReflector();
  _ref46.initReflector();
  _ref47.initReflector();
  _ref48.initReflector();
  _ref49.initReflector();
  _ref50.initReflector();
  _ref51.initReflector();
  _ref52.initReflector();
  _ref53.initReflector();
  _ref54.initReflector();
  _ref55.initReflector();
  _ref56.initReflector();
  _ref57.initReflector();
  _ref58.initReflector();
  _ref59.initReflector();
  _ref60.initReflector();
  _ref61.initReflector();
  _ref62.initReflector();
  _ref63.initReflector();
  _ref64.initReflector();
  _ref65.initReflector();
  _ref66.initReflector();
  _ref67.initReflector();
  _ref68.initReflector();
  _ref69.initReflector();
  _ref70.initReflector();
  _ref71.initReflector();
  _ref72.initReflector();
  _ref73.initReflector();
  _ref74.initReflector();
  _ref75.initReflector();
  _ref76.initReflector();
  _ref77.initReflector();
  _ref78.initReflector();
  _ref79.initReflector();
  _ref80.initReflector();
  _ref81.initReflector();
  _ref82.initReflector();
  _ref83.initReflector();
  _ref84.initReflector();
  _ref85.initReflector();
  _ref86.initReflector();
  _ref87.initReflector();
  _ref88.initReflector();
  _ref89.initReflector();
  _ref90.initReflector();
  _ref91.initReflector();
  _ref92.initReflector();
  _ref93.initReflector();
  _ref94.initReflector();
  _ref95.initReflector();
  _ref96.initReflector();
  _ref97.initReflector();
  _ref98.initReflector();
  _ref99.initReflector();
  _ref100.initReflector();
  _ref101.initReflector();
  _ref102.initReflector();
  _ref103.initReflector();
  _ref104.initReflector();
  _ref105.initReflector();
  _ref106.initReflector();
  _ref107.initReflector();
  _ref108.initReflector();
  _ref109.initReflector();
  _ref110.initReflector();
  _ref111.initReflector();
  _ref112.initReflector();
  _ref113.initReflector();
  _ref114.initReflector();
  _ref115.initReflector();
  _ref116.initReflector();
  _ref117.initReflector();
  _ref118.initReflector();
  _ref119.initReflector();
  _ref120.initReflector();
  _ref121.initReflector();
  _ref122.initReflector();
  _ref123.initReflector();
  _ref124.initReflector();
  _ref125.initReflector();
  _ref126.initReflector();
  _ref127.initReflector();
  _ref128.initReflector();
  _ref129.initReflector();
  _ref130.initReflector();
  _ref131.initReflector();
  _ref132.initReflector();
  _ref133.initReflector();
  _ref134.initReflector();
  _ref135.initReflector();
  _ref136.initReflector();
  _ref137.initReflector();
  _ref138.initReflector();
  _ref139.initReflector();
  _ref140.initReflector();
  _ref141.initReflector();
  _ref142.initReflector();
  _ref143.initReflector();
  _ref144.initReflector();
  _ref145.initReflector();
  _ref146.initReflector();
  _ref147.initReflector();
  _ref148.initReflector();
  _ref149.initReflector();
  _ref150.initReflector();
  _ref151.initReflector();
  _ref152.initReflector();
  _ref153.initReflector();
  _ref154.initReflector();
  _ref155.initReflector();
  _ref156.initReflector();
  _ref157.initReflector();
  _ref158.initReflector();
  _ref159.initReflector();
  _ref160.initReflector();
  _ref161.initReflector();
  _ref162.initReflector();
  _ref163.initReflector();
  _ref164.initReflector();
  _ref165.initReflector();
  _ref166.initReflector();
  _ref167.initReflector();
  _ref168.initReflector();
  _ref169.initReflector();
  _ref170.initReflector();
  _ref171.initReflector();
  _ref172.initReflector();
  _ref173.initReflector();
  _ref174.initReflector();
}
